// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace Experiment1Analysis
{
	// TODO implement datetime parsing
	public struct GazeLogEntry
	{
		public DateTime timestamp;
		public float x;
		public float y;
		public float ref_x;
		public float ref_y;

		public float distance;

		public GazeLogEntry(string entry)
		: this(entry.Split(new char[] { ',' }))
		{

		}

		private GazeLogEntry(string[] contents)
		{
			timestamp = DateTime.ParseExact(contents[0], "HH-mm-ss-fffffff", System.Globalization.CultureInfo.InvariantCulture);
			x = Single.Parse(contents[1]);
			y = Single.Parse(contents[2]);
			ref_x = Single.Parse(contents[3]);
			ref_y = Single.Parse(contents[4]);

			float dx = x - ref_x;
			float dy = y - ref_y;
			
			distance = (float)Math.Sqrt(dx * dx + dy * dy);
		}
	}
}

