// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.IO;


namespace Experiment1Analysis
{
	/*
	Reads from a string
	points to the folder
	
	 */
	public class Participant
	{
		public List<Trial> trials;
		public DemographicData demographics;

		public Participant (string basePath, DemographicData demographics)
		{
			this.demographics = demographics;

			string path = GetParticipantSpecificPath(basePath, demographics.ID);

			// Pair observation and gazelog files
			string[] files = Directory.GetFiles(path);

			// TODO Get and pair observation and gazelog files, generate Trials.
		}

		public void DiscardTrialsWithTooFewReverses(int lowestNumberOfReverses)
		{
			List<Trial> toBeRemoved = new List<Trial>();

			foreach(Trial t in trials)
			{
				if(t.NumberOfReverses < lowestNumberOfReverses)
				{
					toBeRemoved.Add (t);
				}
			}

			foreach(Trial t in toBeRemoved)
			{
				trials.Remove(t);
			}
		}

		public static string GetParticipantSpecificPath(string basePath, int ID)
		{
			string folderName = ID.ToString("0000"); // 4 digits in the folder name
			return Path.Combine(basePath, folderName);
		}
	}
}

